### PR TITLE
Add HackerOne API

### PR DESCRIPTION
**Pull request by saintmalik**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by pawelborkar** [comment]
Thanks for the contribution @saintmalik

**Comment by saintmalik** [comment]
> Thanks for the contribution @saintmalik

(L905) Security section is not in alphabetical order
(L915) description should not exceed 100 characters (currently 116)

looks like its not passing the check due to this error, but i don't understand the "Security section is not in alphabetical order"

**Comment by saintmalik** [comment]
> > Thanks for the contribution @saintmalik
> 
> (L905) Security section is not in alphabetical order
> (L915) description should not exceed 100 characters (currently 116)
> 
> looks like its not passing the check due to this error, but i don't understand the "Security section is not in alphabetical order"

Looks like "Hac" needs to come before "Hav", will mend that

**Comment by pawelborkar** [comment]
> Looks like "Hac" needs to come before "Hav", will mend that

Absolutely.

**Comment by saintmalik** [comment]
> > Looks like "Hac" needs to come before "Hav", will mend that
> 
> Absolutely.



> > Looks like "Hac" needs to come before "Hav", will mend that
> 
> Absolutely.

All done

**Comment by pawelborkar** [comment]
> don't forget to squash your commits into a single one.

Required.

**Comment by saintmalik** [comment]
> > don't forget to squash your commits into a single one.
> 
> Required.

Am having issues with squashing those commit, mind if i create another pull request and close this?

**Comment by pawelborkar** [comment]
Yeah, Go ahead.

**Comment by saintmalik** [comment]
> Yeah, Go ahead.

Thanks

 Reopened here #1896

**Pull request closed without merging**
