### PR TITLE
Added Tisane. Corrected a typo in Semantria

### PR DESCRIPTION
**Pull request by vadim-berman**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marekdano** [comment]
@vadim-berman Thanks for the contribution!
Can you please solve the conflict?

**Comment by marekdano** [comment]
@vadim-berman Thanks for the contribution!
Can you please solve the conflict?

**Comment by vadim-berman** [comment]
Done! Thank you, @marekdano.

**Comment by vadim-berman** [comment]
Sorry, @marekdano, looks like the tests failed because of an old URL that was later removed. What do I do now?

**Comment by marekdano** [comment]
@vadim-berman thanks for the update 
You've added a new record of `Language Identification https://rapidapi.com/BigLobster/api/language-identification-prediction` which is not in the README anymore. Can you please remove it from the PR?
`tisane.ai` returns 406 which is not covered by the validation script. You don't need to worry about it.

**Comment by vadim-berman** [comment]
Should be fine now. I also removed the other failing URLs.

**Comment by vadim-berman** [comment]
I see more old links are failing. Hope I don't have to clean up everything, I only added one.

**Comment by PawelBorkar** [comment]
Can you please [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) the commits into a single one?

**Comment by marekdano** [comment]
@vadim-berman thanks for solving the conflict.
Can I ask you to not remove the broken links in this PR. Just to have Tisane API and a corrected typo in Semantria, please?
If you still want to remove the broken links, please create a new PR.
When you finish please [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) your commits or if it's easy for you just create a new PR and this PR will be closed.

**Comment by vadim-berman** [comment]
Thank you, @marekdano and @PawelBorkar. I only removed it because of the errors, but naturally, I'll be more than happy to leave it all alone. Should I roll back my commits before squashing them?

**Comment by vadim-berman** [comment]
Sorry, guys, it was more simple to delete the entire repository and create a [new pull request](https://github.com/public-apis/public-apis/pull/1606). Thanks both.

**Pull request closed without merging**
