### PR TITLE
Add PyOpenD6 to Games & Comics

### PR DESCRIPTION
**Pull request by oxr463**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] <s>Any category I am creating has the minimum requirement of 3 items</s>
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by fintzd — APPROVED** [review]
LGTM

**Review by richardsonmark316 — APPROVED** [review]

**Comment by matheusfelipeog** [comment]
Hi @oxr463 :)

I didn't find the API documentation, do you have any links about it? We only accept APIs with documentation, official or not.

**Comment by oxr463** [comment]
> Hi @oxr463 :)
> 
> I didn't find the API documentation, do you have any links about it? We only accept APIs with documentation, official or not.

Try this, https://hexgear.gitlab.io/pyopendsix

**Comment by matheusfelipeog** [comment]
And I also think there's a problem with the redirect as it's returning [HTTP code 308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) in our tests. If we can't solve this, we can't accept this API.

**Comment by matheusfelipeog** [comment]
> Try this, https://hexgear.gitlab.io/pyopendsix

Sounds good to me, but there is no reference to the base URL of the API (https://pyopendsix.herokuapp.com/api/v1/info/) you put in this PR, It only contains the endpoints.

**Pull request closed without merging**
