### PR TITLE
Add DevITJobs Job API

### PR DESCRIPTION
**Pull request by MariaAbadi**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by MariaAbadi** [comment]
@andrew would you mind checking if it's fine? 🙂

**Comment by MariaAbadi** [comment]
Hi @andrew @gstark do you mind checking it? :)

**Comment by MariaAbadi** [comment]
@marekdano would you mind? :)

**Comment by marekdano** [comment]
> @marekdano would you mind? :)

Thanks for the contribution @MariaAbadi! 
We're doing our best to solve/merge all the PRs. We merge the old ones first. For more ref check #1604

**Review by VChernomYA — APPROVED** [review]

**Comment by VChernomYA** [comment]
README.md

**Comment by MariaAbadi** [comment]
Thanks @VChernomYA, should be solved 🙂

**Review by VChernomYA — APPROVED** [review]

**Review by VChernomYA — APPROVED** [review]

**Review by VChernomYA — APPROVED** [review]

**Comment by MariaAbadi** [comment]
@PawelBorkar @marekdano @VChernomYA I moved the PR to: https://github.com/public-apis/public-apis/pull/1686 because I had some troubles with the squash 😊 
Closing this one.

**Pull request closed without merging**
