### PR TITLE
Added "The Office API" from https://www.officeapi.dev/

### PR DESCRIPTION
**Pull request by rappos**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by artemShvalev** [comment]
Nice! Thank you, I'm lovely this show

**Comment by PawelBorkar** [comment]
Thanks for your contribution @rappos.
Can you please resolve the conflicts?

**Comment by rappos** [comment]
> Thanks for your contribution @rappos.
> Can you please resolve the conflicts?

What is the problem, I do not understand what "Resolve conflict required" means?

**Comment by PawelBorkar** [comment]
> > Thanks for your contribution @rappos.
> > Can you please resolve the conflicts?
> 
> What is the problem, I do not understand what "Resolve conflict required" means?

Refer [this](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github)

**Comment by rappos** [comment]
Will send a new PR tomorrow

**Pull request closed without merging**
