### PR TITLE
Add Black History Facts to Open Data

### PR DESCRIPTION
**Pull request by collinpartee**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by pawelborkar — APPROVED** [review]
Thanks for the contribution @collinpartee

**Comment by collinpartee** [comment]
I see the Validate Readme test failed on my api docs url. Do I need to format it differently?

**Review by pawelborkar — CHANGES_REQUESTED** [review]
I think there's an issue with the redirect since it's returning 308 [Ref.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308)

**Comment by matheusfelipeog** [comment]
This PR is inactive, so the API was added in another PR/commit.

More information at: #2002

**Pull request closed without merging**
