### PR TITLE
added OpenCorporates

### PR DESCRIPTION
**Pull request by bogdanlalu**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by yannbertrand** [comment]
Can you link to the API documentation?

**Comment by bogdanlalu** [comment]
@yannbertrand Sure, shall I submit a new PR? Not sure how to make the change at this stage. The link is http://api.opencorporates.com/documentation/API-Reference

**Comment by yannbertrand** [comment]
You can do it in this one! Please squash your commits and force push to your branch 😉

**Comment by bogdanlalu** [comment]
@yannbertrand I think I was able to do it. Please let me know if there are any issues as I am relatively new at this.

**Comment by yannbertrand** [comment]
You did great 😄 thank you very much

**Pull request merged**
