### PR TITLE
Add Decathlon APIs

### PR DESCRIPTION
**Pull request by CaioBianchi**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by davemachado** [comment]
please address build failures - thanks.

**Comment by CaioBianchi** [comment]
Done @davemachado 
Thanks!

**Comment by CaioBianchi** [comment]
Any updates on this?

**Comment by davemachado** [comment]
Hi @CaioBianchi , we generally look to list single entries per service, even if that service offers multiple datasets. Can you please squash these two in one?

**Comment by CaioBianchi** [comment]
Hi @davemachado,

These are 2 different APIs that serve 2 different purposes. I don't see how I could merge them into 1 entry, unless I link to our developers' portal (?)

**Comment by CaioBianchi** [comment]
@davemachado Is this something that can be done or not?

**Comment by davemachado** [comment]
Hi @CaioBianchi , sorry for the hiatus. Can you please add one link to the entire developer portal? Thanks.

**Pull request closed without merging**
