### PR TITLE
Add categories and apis

### PR DESCRIPTION
**Pull request by Rchristiani**
Initial pass at adding categories and additional API's!

### CODE REVIEW

**Review by Yedfree — APPROVED** [review]

**Comment by Adore-TEST** [comment]
test

**Comment by Adore-TEST** [comment]
test2

**Comment by Adore-TEST** [comment]
test3

**Comment by Adore-TEST** [comment]
test4

**Comment by Adore-TEST** [comment]
test5

**Comment by Adore-TEST** [comment]
test6

**Comment by Adore-TEST** [comment]
test7

**Comment by Adore-TEST** [comment]
public-apis -- https://github.com/public-apis/public-apis
free-programming-books -- https://github.com/EbookFoundation/free-programming-books
system-design-primer -- https://github.com/donnemartin/system-design-primer
awesome-python -- https://github.com/vinta/awesome-python
project-based-learning -- https://github.com/practical-tutorials/project-based-learning

**Comment by Adore-TEST** [comment]
test8

**Comment by Adore-TEST** [comment]
test9

**Comment by Adore-TEST** [comment]
test10

**Pull request merged**
