### PR TITLE
Add Listen Notes (podcast api).

### PR DESCRIPTION
**Pull request by wenbinf**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the contributing guide
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been squashed into a single commit

### CODE REVIEW

**Comment by yannbertrand** [comment]
Hey, sorry for the delay.

Please do 2 seperate PRs.

**Comment by wenbinf** [comment]
> Hey, sorry for the delay.
> 
> Please do 2 separate PRs.

Cool. Updated to only adding the new api.

Will change the section name after this is merged.

**Comment by yannbertrand** [comment]
Be careful, you're deleting another API!

**Comment by wenbinf** [comment]
This PR is dragging too long to merge. I will start a new PR, based on the latest master branch.

**Pull request closed without merging**
