### PR TITLE
Added API of 7digital

### PR DESCRIPTION
**Pull request by Nirzak**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

### CODE REVIEW

**Comment by marekdano** [comment]
Thanks for the contribution, @Nirzak!

Does the API have a free-tier plan, please? I could find no details about it.

**Comment by Nirzak** [comment]
> Thanks for the contribution, @Nirzak!
> 
> Does the API have a free-tier plan, please? I could find no details about it.

Yes it is free to use. But however from their API documentation there may be a daily usage limit for the free plan.

**Comment by marekdano** [comment]
> Yes it is free to use. But however, from their API documentation, I came to know that there may be a daily usage limit for the free plan.

Can you please provide the link to confirm it?

**Comment by Nirzak** [comment]
> > Yes it is free to use. But however, from their API documentation, I came to know that there may be a daily usage limit for the free plan.
> 
> Can you please provide the link to confirm it?

Hi, it's in this link https://docs.7digital.com/reference#usage-limits on the usage limit section. Sorry for late response.

**Pull request merged**
