### PR TITLE
Added Urban Dictionary API

### PR DESCRIPTION
**Pull request by mohammedfarish**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by PawelBorkar** [comment]
Thanks for the contribution @mohammedfarish 
Please [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) the commits into a single one.

**Comment by PawelBorkar** [comment]
It's lacking documentation.

**Review by matheusfelipeog — COMMENTED** [review]
@PawelBorkar this API has no public documentation and no information about it (example: description, auth, https, cors).

I think it's better not to accept this PR. 😅

**Comment by PawelBorkar** [comment]
Thanks for the review @matheusfelipeog. I was also thinking the same.

**Comment by PawelBorkar** [comment]
As @matheusfelipeog has stated in his [comment](https://github.com/public-apis/public-apis/pull/1496#pullrequestreview-634055738) and I had also mentioned it before that the API is lacking public documentation and other necessary information required to consider and merge the PR into the repo.
Unfortunately we cannot accept your PR. 

Thanks for your efforts. We encourage you to make future PRs having API with public documentation and other necessary info. so we can merged it into the repo.

**Pull request closed without merging**
