### PR TITLE
Updated API link for Indian Railways

### LINKED ISSUE #1360: Remove this Indian Railways (http://api.erail.in) False api #important
# Please remove this from **apiurl** list it's a false api 
### by checking it manually its look like a someone's personal website please check and remove it
* Link - [False api link](http://api.erail.in/)

### PR DESCRIPTION
**Pull request by md-yaseen**
Closes #1360 

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by md-yaseen** [comment]
Fixes #1360 

Removed the false API link.

**Comment by yannbertrand** [comment]
Looks like https://www.affiliate.confirmtkt.com/ is not an Indian Railways API and doesn't provide an API.

Will accept the PR if you simply remove the Indian Railways API line.

**Comment by md-yaseen** [comment]
Hi @yannbertrand 
I have removed the Indian Railways API Line as suggested.

**Comment by yannbertrand** [comment]
Thanks

**Pull request merged**
