### PR TITLE
Add Autochess VNG API (Unofficial)

### PR DESCRIPTION
**Pull request by didadadida93**
Add link and description about Autochess VNG API to `README.md` file.

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marekdano** [comment]
Thanks for the contribution @didadadida93!
Can you please resolve the conflict?

**Comment by didadadida93** [comment]
Alright, I will do

**Comment by didadadida93** [comment]
done @marekdano :+1:

**Comment by marekdano** [comment]
Thanks for the update @didadadida93! But now you're committing lots of changes. 
I think the best is to close this PR and create a new one just with your API record.

**Comment by didadadida93** [comment]
good idea :+1:

**Pull request closed without merging**
