### PR TITLE
Added GitHub Actions

### PR DESCRIPTION
**Pull request by roelofr**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

----

Since I blew up the PR list with all my fixes concerning the covid-19 change, I also noticed that pull-requests don't get validated.

Since I don't know why Travis didn't work, and I do very much know how GitHub actions work, I added a check to GitHub actions that runs on pull requests and after pushing to the repo.

Let me know if this is useful.

### CODE REVIEW

**Comment by yannbertrand** [comment]
That's an awesome contribution!

As I don't have access to public-apis settings, I can't add Travis hook validation (which [is running](https://travis-ci.org/github/public-apis/public-apis) on each PR). Hopefully, I don't need any settings change for GitHub Actions to work directly...

Let's try and fix it if needed! If we can make it, we'll need to update the status badge in the readme 😉

**Comment by yannbertrand** [comment]
See #1194

**Comment by roelofr** [comment]
Houston, we got errors 🎉

**Comment by yannbertrand** [comment]
That's great!

I'm not that familiar with Actions, could it be possible to only have one triggered build instead of two?

And by any chance, run builds for all the opened PR 😅

**Pull request merged**
