### PR TITLE
Added Superhero API

### PR DESCRIPTION
**Pull request by vrushank-desai**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [X] Your additions are ordered alphabetically
- [X] Your submission has a useful description
- [X] The description does not end with punctuation
- [X] Each table column should be padded with one space on either side
- [X] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by vrushank-desai** [comment]
CI build failed as title has ".. API" in it. Updated it to SuperHeroes as only SuperHero would be rather vague

**Comment by yannbertrand** [comment]
Hey, thank you for that addition and sorry for the delay.

There is a typo on "Villians", can you please fix it?

**Comment by vrushank-desai** [comment]
Typo fixed. Please let know in case of any other changes

**Comment by yannbertrand** [comment]
Thank you 🎉

**Pull request merged**
