### PR TITLE
Update CORS from many APIs

### PR DESCRIPTION
**Pull request by codewithpom**
Actually I submitted a PR to the axolptl repository to make it CORS less so that we can use it in website https://github.com/AxolotlAPI/axolotlapi.py/pull/2 but I forgot to tell you back sorry for that but now please have a look.

### CODE REVIEW

**Comment by codewithpom** [comment]
I now updated CORS for many other sites as well @matheusfelipeog please have a look.

**Comment by salsjing** [comment]
ya

**Comment by DenysAptikieiev** [comment]
Great

**Comment by codewithpom** [comment]
Thanks

**Review by techcareqa — APPROVED** [review]

**Comment by codewithpom** [comment]
@matheusfelipeog Thanks and I would like to open some more PR if you allow.

**Comment by codewithpom** [comment]
@matheusfelipeog if you will not be sad can you make me a collaborator now 😅

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog if you will not be sad can you make me a collaborator now 😅

Thanks for your interest in becoming a collaborator for this project, but unfortunately I don't have administrative rights to add new ones. Also, I believe it is not necessary at the moment.

**Pull request merged**
