### PR TITLE
Removed broken links and fixed python script

### LINKED ISSUE #1417: Broken links in README.md
There are several links that are broken in the README.md file based on the report from the link validation activity.

Below is the log from the script. It contains the error code reported and the link on which it was reported. 

```
Run build/validate_links.py ${FORMAT_FILE}
Validating 654 links...
404: https://github.com/public-apis/public-apis/workflows/Run%20tests/badge.svg](https://github.com/public-apis/public-apis/actions?query=workflow%3A%22Run+tests%22
404: https://github.com/davemachado/public-api!
405: https://docs.thecatapi.com/
404: https://www.petfinder.com/developers/v2/docs/
404: http://shibe.online/
404: https://otx.alienvault.com/api/
ERR: Content purported to be compressed with gzip but failed to decompress. : https://www.block.io/docs/basic
405: https://api.coinpaprika.com
500: https://ifsc.razorpay.com/
404: http://www.amiiboapi.com/
404: https://api.igdb.com/
404: https://indian-cities-api-nocbegfhqg.now.sh/
SOC: Remote end closed connection without response : https://www.dati.gov.it/
SOC: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) : http://www.flutrack.org/
405: https://api.graphql.jobs
405: https://www.themuse.com/developers/api/v2
SOC: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) : https://developer.nytimes.com/
SOC: The read operation timed out : https://libraries.io/api
404: https://go.developer.ebay.com/
ERR: Unable to find the server at dev.mixer.com : https://dev.mixer.com/
501: https://core.telegram.org/bots/api
501: https://core.telegram.org/api
404: https://www.tumblr.com/docs/en/api/v2
418: https://vk.com/dev/sites
501: https://developer.jcdecaux.com/
404: http://nflarrest.com/api/
404: http://avatars.adorable.io
503: https://www.ups.com/upsdeveloperkit
SOC: timed out : http://www.aisweb.aer.mil.br/api/doc/index.cfm
ERR: Unable to find the server at developer.goibibo.com : https://developer.goibibo.com/docs
404: https://api.tfl.gov.uk
404: http://datamine.mta.info/
SOC: [Errno 104] Connection reset by peer : http://reisapi.ruter.no/help
404: https://developer.translink.ca/
```

### PR DESCRIPTION
**Pull request by SitramSoft**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

This PR resolves #1417

I changed the regex expression used in extracting the links from the README.md file to one that worked better. The regex was tested in https://regex101.com/ against the old one and to make sure that no links were missed.

The HTTP request HEAD was not supported by some links so I changed it to a regular GET method. I increased timeout from 5s to 10s because I was getting a few false positive timeout errors.

All links reported with error 404 which were not working were removed from the README.md file.

### CODE REVIEW

**Comment by SitramSoft** [comment]
I still get 2 errors when running the script but the links works. Any suggestions on what to do with then?

404: https://www.petfinder.com/developers/v2/docs/
ERR: Content purported to be compressed with gzip but failed to decompress. : https://www.block.io/docs/basic

**Comment by yannbertrand** [comment]
Hey, let's merge this one first. Thanks again

**Comment by yannbertrand** [comment]
Here's the errors I have now:

errors

**Comment by SitramSoft** [comment]
Can you paste the code not the picture so I can check them from my phone?

For most of these links I don't understand why we get errors. Whar do you want to do with them?

**Comment by yannbertrand** [comment]
https://github.com/public-apis/public-apis/runs/1260844756?check_suite_focus=true

**Comment by yannbertrand** [comment]
```
Validating 641 links...
404: https://www.petfinder.com/developers/v2/docs/
ERR: Content purported to be compressed with gzip but failed to decompress. : https://www.block.io/docs/basic
404: http://www.amiiboapi.com/
ERR: Redirected but the response is missing a Location: header. : https://sv443.net/jokeapi
SOC: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) : http://www.flutrack.org/
SOC: _ssl.c:835: The handshake operation timed out : https://currentsapi.services/
SOC: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) : https://developer.nytimes.com/
```

**Comment by yannbertrand** [comment]
I can't work on it these days but we have to find out if that's related to public apis script or the pages themselves

**Comment by SitramSoft** [comment]
404: https://www.petfinder.com/developers/v2/docs/ 

ERR: Content purported to be compressed with gzip but failed to decompress. : https://www.block.io/docs/basic 

404: http://www.amiiboapi.com/ 

ERR: Redirected but the response is missing a Location: header. : https://sv443.net/jokeapi 

SOC: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) : http://www.flutrack.org/ 

SOC: _ssl.c:835: The handshake operation timed out : https://currentsapi.services/ 

SOC: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) : https://developer.nytimes.com/

I already saw the log from last run of the action but I get fewer errors then in your picture. Can you check again if you see the same errors as the ones I copied above?

**Pull request merged**
