### PR TITLE
Add Zestful API

### PR DESCRIPTION
**Pull request by mtlynch**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Comment by marekdano** [comment]
@mtlynch Thanks for your contribution! Can you please resolve the conflict before our merging?

**Comment by mtlynch** [comment]
Sure, done.

**Comment by marekdano** [comment]
@mtlynch do you think you'll be able to fix the failing tests under the `Validate` check that ran on Github Actions? 
Screenshot 2021-03-19 at 20 30 27

**Comment by mtlynch** [comment]
Those failures are unrelated to my change. My change is on line 372.

**Comment by matheusfelipeog** [comment]
> Those failures are unrelated to my change. My change is on line 372.

You're right.

Thanks for contribution @mtlynch 😆

**Pull request merged**
