### PR TITLE
Add AIForThai API

### PR DESCRIPTION
**Pull request by champnc**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by pawelborkar** [comment]
Is it free or not? I didn't find any information regarding the pricing.

**Comment by champnc** [comment]
> Is it free or not? I didn't find any information regarding the pricing.

Yes It's free. But have limited total request.

**Review by Jeriko698 — APPROVED** [review]

**Comment by pawelborkar** [comment]
> Yes It's free. But have limited total request.
Please provide the URL for reference

**Comment by champnc** [comment]
> > Yes It's free. But have limited total request.
> 
> Please provide the URL for reference

https://aiforthai.in.th/index.php in their FAQs tab.

**Review by matheusfelipeog — APPROVED** [review]
I checked this API, it looks all right.

Thanks for your contribution @champnc 😄

**Pull request merged**
