### PR TITLE
Add Rick and Morty

### PR DESCRIPTION
**Pull request by zakarialaoui10**

### CODE REVIEW

**Review by hingcat — CHANGES_REQUESTED** [review]
不要儲存

**Review by hingcat — CHANGES_REQUESTED** [review]
不要儲存

**Review by hingcat — CHANGES_REQUESTED** [review]
不要儲存

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @zakarialaoui10, but this API is already listed here. 😅

See in Games & Comics section

**Pull request closed without merging**
