### PR TITLE
Add Fun Fact API

### PR DESCRIPTION
**Pull request by aakhilv**
- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by matheusfelipeog — APPROVED** [review]
Thanks for your contribution @aakhilv ❤

**Comment by tedi33** [comment]
Ok

**Comment by JoshuaBehrens** [comment]
Is the service down?

image

**Comment by aakhilv** [comment]
Oh sorry, I had changed the domain it's on.

You can now find it at [https://api.aakhilv.me](https://api.aakhilv.me)

**Comment by matheusfelipeog** [comment]
> Oh sorry, I had changed the domain it's on.
> 
> You can now find it at https://api.aakhilv.me

This API was removed in https://github.com/public-apis/public-apis/commit/494e5977b302c428c734b67c05803277c8b4c0c9 because it was broken. Thanks for letting me know that her url has been changed.

I will add it to the list again

**Comment by matheusfelipeog** [comment]
Done ✅

ref: https://github.com/public-apis/public-apis/commit/3c5343ae1d71276b25a99df8446c78ff06e28c96

**Pull request merged**
