### PR TITLE
[-] ErosNow API Replacement

### PR DESCRIPTION
**Pull request by 0x0is1**
As previously provided ErosNow api is not active anymore, i have proposal to use this API instead. Although i have no idea how the older API used to look like as i noticed today, so it should be peer reviewed by previous contributor as well as the repo reviewers.

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by 0x0is1** [comment]
@ankit64jangir you should take a look on changes, as it was proposed by you. Is it right? And can you confirm you are too having problem while accessing older API?

**Comment by 0x0is1** [comment]
@pawelborkar as the last contributor of this module @ankit64jangir isn't responding, i am 98% sure this is the correct replacement of ErosNow API which they haven't documented it yet. Should we accept it or wait long for original contributor to respond?

**Comment by pawelborkar** [comment]
@0x0is1 We should wait for some more days.

**Comment by pawelborkar** [comment]
Hey @0x0is1,
As we waited for so long for the response from @ankit64jangir but he haven't responded yet, so I'm gonna accept this replacement for the ErosNow API.

Feel free to update it with the official one whenever it's available in the future.

Thanks 😊

**Comment by cameron187187** [comment]
Being scammed please stop helping this account!!!’ They have taken overSent from my iPhone

**Comment by 0x0is1** [comment]
Bruh.

**Pull request merged**
