### PR TITLE
Add Portfolio Optimizer API

### PR DESCRIPTION
**Pull request by lequant40**
- [X] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [X] My addition is ordered alphabetically
- [X] My submission has a useful description
- [X] The description does not have more than 100 characters
- [X] The description does not end with punctuation
- [X] Each table column is padded with one space on either side
- [X] I have searched the repository for any relevant issues or pull requests
- [X] Any category I am creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by pawelborkar** [comment]
> Portfolio Optimizer is free to use, but not free to run.
> 
> In order to obtain an API key and benefit from higher API limits, a small participation to Portfolio Optimizer running costs is required.

The anonymous user limitations are much lower as well

**Comment by lequant40** [comment]
Hi @pawelborkar !

Not sure what should I do following your remark? 

Portfolio Optimizer do not **require** an API key to work, you can try it yourself using the on line console -> [https://docs.portfoliooptimizer.io/](https://docs.portfoliooptimizer.io/)

So, updating the PR with _apiKey_ would be misleading as there is a 100% unauthenticated mode.

Waiting for your feeback!

Roman

**Review by matheusfelipeog — APPROVED** [review]
This API is valid and is working correctly.

Thanks for your contribution @lequant40 ;)

**Comment by pawelborkar** [comment]
Hey @lequant40 

>Portfolio Optimizer do not require an API key to work, you can try it yourself using the on line console -> https://docs.portfoliooptimizer.io/

Yup, I have read its documentation.

>So, updating the PR with apiKey would be misleading as there is a 100% unauthenticated mode.

Absolutely, I didn't wanted you to do it either.
I was just a little bit concerned with the limitations they're imposing on the anonymous usage of the API for more information refer #1856 

Thanks.

**Pull request merged**
