### PR TITLE
Added Fairfield Programming Association

### PR DESCRIPTION
**Pull request by William-McGonagle**
- [X] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [X] My addition is ordered alphabetically
- [X] My submission has a useful description
- [X] The description does not have more than 100 characters
- [X] The description does not end with punctuation
- [X] Each table column is padded with one space on either side
- [X] I have searched the repository for any relevant issues or pull requests
- [X] Any category I am creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by William-McGonagle** [comment]
Should I change the link to the code instead?

[Code](https://github.com/fairfield-programming/backend-server)

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @William-McGonagle ;)

> Should I change the link to the code instead?
> 
> [Repository API with Docs](https://github.com/fairfield-programming/backend-server)

Well, the focus of this project doesn't seem to me to be related to a duck joke API, but rather to coding competitions.

That's why I believe it's not valid to list this project here. 😅

**Comment by William-McGonagle** [comment]
So the duck joke API isn't going to be merged?

**Comment by matheusfelipeog** [comment]
> So the duck joke API isn't going to be merged?

Unfortunately it cannot be added @William-McGonagle.

This API is a subproject of another project without the same goal.

Note that if I accept this API, any other project can create a random API just to add it to this list for marketing purposes for the main project.

**Comment by William-McGonagle** [comment]
Ok- that makes sense. Thank you for your time!

**Comment by William-McGonagle** [comment]
@matheusfelipeog Hey- if I added the whole api onto here would that qualify. Feel free to say no, I was just sitting in bed and thought of that. But it might've been a stupid question. :)

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog Hey- if I added the whole api onto here would that qualify. Feel free to say no, I was just sitting in bed and thought of that. But it might've been a stupid question. :)

@William-McGonagle If this API stops being a sub-project and becomes the main project with the aim of providing duck jokes, having good documentation and is in accordance with our contribution guide, I believe I can accept it ;)

**Pull request closed without merging**
