### PR TITLE
Add TrailerAddict API

### PR DESCRIPTION
**Pull request by chauxvive**
- [X] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [X] My addition is ordered alphabetically
- [X] My submission has a useful description
- [X] The description does not have more than 100 characters
- [X] The description does not end with punctuation
- [X] Each table column is padded with one space on either side
- [X] I have searched the repository for any relevant issues or pull requests
- [X] Any category I am creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by chauxvive** [comment]
Added "TrailerAddict" API. Many thanks!

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @chauxvive ;)

Only add APIs that are not listed for review, please. 😅

**Comment by chauxvive** [comment]
Hi, Sorry, not listed for review? What does that mean in context? 

Sorry, I'm very new to all this... Thanks again.

**Comment by matheusfelipeog** [comment]
New York Times Movie Reviews is already listed here, in News section

**Pull request closed without merging**
