### PR TITLE
Add open data, Poland goverment

### PR DESCRIPTION
**Pull request by olekstomek**
The Dane.gov.pl website pursues the objective of the Central Public Data Repository in Poland, provides data also via API

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @olekstomek ;)

You've made a big change to the `README.md` file, I don't think it's intentional.

Can you fix that and just add the [Open Government, Poland](https://dane.gov.pl/en) API to the list?

You can fix it in this PR or open a new PR.

**Comment by olekstomek** [comment]
It was accidental. Currently I see that after pressing `ctrl + s` in Visual Studio Code the formatting changes (probably some plugin). :) I reverted previous formatting.

**Comment by olekstomek** [comment]
I see a failure in the PR validation step:
> +| [Open Government, Poland](https://dane.gov.pl/en) | Poland Government Open Data | No | Yes | Unknown |
> ------- END ADDITIONS ------
> Running link validation...
> Checking for duplicated links...
> No duplicate links
> Validating 1 links...
> ERR:SOC: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131) : https://dane.gov.pl/en
> Error: Process completed with exit code 1.

https://github.com/public-apis/public-apis/blob/2ad86730942e37afb0c8668301dcd7fc2e92d851/build/validate_links.py#L71

I know it's not up to me. PR is correct. The same problem for example here: https://github.com/ytdl-org/youtube-dl/issues/22335
You can check more information in [SSL Report](https://www.ssllabs.com/ssltest/analyze.html?d=dane.gov.pl) for this domain:
image
@matheusfelipeog what in this case?

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog what in this case?

@olekstomek We do not accept APIs that break tests.

So, you have two options: Ask the API owner to fix this problem on their server or you can close this PR.

**Review by matheusfelipeog — COMMENTED** [review]
> @matheusfelipeog what in this case?

@olekstomek We do not accept APIs that break tests.

So, you have two options: Ask the API owner to fix this problem on their server or you can close this PR.

**Comment by olekstomek** [comment]
OK, I will ask them to fix this problem. We'll see what they do and I'll come back with an answer.

**Comment by matheusfelipeog** [comment]
> OK, I will ask them to fix this problem. We'll see what they do and I'll come back with an answer.

Ok. Good luck ;)

**Comment by olekstomek** [comment]
@matheusfelipeog it was fixed. :) Tests passed.
I got information that CORS should be yes but any CORS restrictions are disabled.

image

**Review by matheusfelipeog — APPROVED** [review]
Perfect @olekstomek ✔

A big THANKS for your effort in solving this, we appreciate it. ❤️

**Comment by olekstomek** [comment]
My pleasure, I like it. :)

**Pull request merged**
