### PR TITLE
Add Classify API to Security

### PR DESCRIPTION
**Pull request by cheatsnake**
- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by cheatsnake** [comment]
@pawelborkar please approve

**Comment by pawelborkar** [comment]
Hi @cheatsnake, Thanks for opening this PR. 

Heroku is showing application error message.
Fix it and let me know.

**Comment by cheatsnake** [comment]
> Hi @cheatsnake, Thanks for opening this PR.
> 
> Heroku is showing application error message. Fix it and let me know.

Thanks for the quick response. I opened the site without any problems and made a POST request for the endpoints of the application. Live playground: https://jsitor.com/-WpfRhxbj
You may have had problems due to the fact that the heroku site was in sleep mode, usually you need to wait a few seconds because of this.

**Comment by pawelborkar** [comment]
> Thanks for the quick response
You're welcome.

And thanks for the contribution @cheatsnake

**Pull request merged**
