### PR TITLE
Added kvdb.io

### PR DESCRIPTION
**Pull request by rubenhorn**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by yannbertrand** [comment]
I'm sorry, but we can't accept these kinds of products. Remember this repo is not a marketing tool, but a tool to help the community build applications and use free, public APIs quickly and easily.

**Comment by rubenhorn** [comment]
Not sure why this is disqualified.
It has a free tier that is very much useful as a remote config store.
What makes this different from myjson.com? The fact it has rate limits and a paid plan?
(I am not affiliated with kvdb.io)

**Comment by rubenhorn** [comment]
Not sure why this is disqualified.
It has a free tier that is very much useful as a remote config store.
What makes this different from M
(I am not affiliated with kvdb.io)

**Comment by yannbertrand** [comment]
In my sense, the fact that you need to create an account to start using the service is a no go.

You'll find plenty of APIs that actually requires authentication in this repo but I believe it's shouldn't belong here. We probably have been too lax in the past. I'll have to browse them all and remove the ones that don't really fit in.

Is it clearer?

**Pull request closed without merging**
