### PR TITLE
Add Lecto Translation to Text Analysis

### PR DESCRIPTION
**Pull request by AgrimPrasad**
Lecto Translation API provides a Machine Translation API with a free tier, as well as reasonable prices. Lecto Translation API is also integrated with Loco Translate, the leading Wordpress Translation Management plugin.

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @AgrimPrasad, but apparently this API is not free. It provides an API key only for limited trials, when this trial period runs out it is necessary to hire one of its plans.

ref 1: https://dashboard.lecto.ai/docs
ref 2: https://lecto.ai/#pricing
ref 3: https://dashboard.lecto.ai/pricing

**Comment by AgrimPrasad** [comment]
> Thanks for your contribution @AgrimPrasad, but apparently this API is not free. It provides an API key only for limited trials, when this trial period runs out it is necessary to hire one of its plans.
> 
> ref 1: [dashboard.lecto.ai/docs](https://dashboard.lecto.ai/docs) ref 2: [lecto.ai/#pricing](https://lecto.ai/#pricing) ref 3: [dashboard.lecto.ai/pricing](https://dashboard.lecto.ai/pricing)

Thanks for the review. There is a Free Basic plan here which rolls over every month. Can that be linked? https://rapidapi.com/lecto-lecto-default/api/lecto-translation/pricing

**Comment by matheusfelipeog** [comment]
> Thanks for the review. There is a Free Basic plan here which rolls over every month. Can that be linked? https://rapidapi.com/lecto-lecto-default/api/lecto-translation/pricing

Yes, this one can be added.

Sorry, I didn't see this in the footer of the page 😅

**Comment by matheusfelipeog** [comment]
Can you change the link to https://rapidapi.com/lecto-lecto-default/api/lecto-translation/ please?

**Comment by AgrimPrasad** [comment]
> Can you change the link to [rapidapi.com/lecto-lecto-default/api/lecto-translation](https://rapidapi.com/lecto-lecto-default/api/lecto-translation/) please?

Updated, please check.

**Review by matheusfelipeog — CHANGES_REQUESTED** [review]
Can you resolve this review, please?

**Comment by AgrimPrasad** [comment]
> Can you resolve this review, please?

Thanks, I've applied your suggestion now, please check.

**Review by matheusfelipeog — APPROVED** [review]
Now it's ok ✔

Thanks for the update @AgrimPrasad <3

**Pull request merged**
