### PR TITLE
Added Freesound api

### PR DESCRIPTION
**Pull request by littlemousey**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [ V ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ V ] Your additions are ordered alphabetically
- [ V ] Your submission has a useful description
- [ V ] The description does not end with punctuation
- [ V ] Each table column should be padded with one space on either side
- [ V ] You have searched the repository for any relevant issues or pull requests
- [ X ] Any category you are creating has the minimum requirement of 3 items
- [ V ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by yannbertrand** [comment]
Hey sorry for the delay.

Can you please just set `apiKey`? I've seen that you can choose between `apiKey` and `OAuth` but we're still not sure on how to display that information in this list...

**Comment by littlemousey** [comment]
I changed it to `apiKey` and merged master into my branch. But apparently Github recognizes some changes/conflicts which my editor does not see...? Spacing or something?

**Comment by yannbertrand** [comment]
Your editor seems to add spaces to improve table viewing. You probably have some markdown extension that does that...

**Comment by yannbertrand** [comment]
Closing this PR as I have no news on it. Feel free to reopen it if you work on it again

**Pull request closed without merging**
