### PR TITLE
Added Inshorts News API

### PR DESCRIPTION
**Pull request by FayasNoushad**
Api :- https://inshortsapi.vercel.app

### CODE REVIEW

**Comment by FayasNoushad** [comment]
[/] My submission is formatted according to the guidelines in the contributing guide
[/] My addition is ordered alphabetically
[/] My submission has a useful description
[/] The description does not end with punctuation
[/] Each table column is padded with one space on either side
[/] I have searched the repository for any relevant issues or pull requests
[/] Any category I am creating has the minimum requirement of 3 items
[/] All changes have been squashed into a single commit

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @FayasNoushad :)

Can you tell me what it is for and how to use this API? that doesn't seem very clear to me:

image

**Comment by FayasNoushad** [comment]
> Thanks for your contribution @FayasNoushad :)
> 
> Can you tell me what it is for and how to use this API? that doesn't seem very clear to me:
> 
> image

Documentation :- https://github.com/cyberboysumanjay/Inshorts-News-API

**Comment by matheusfelipeog** [comment]
> Documentation :- https://github.com/cyberboysumanjay/Inshorts-News-API

@FayasNoushad Oh right. Can you update the API link for this, please?

**Comment by FayasNoushad** [comment]
> > Documentation :- https://github.com/cyberboysumanjay/Inshorts-News-API
> 
> @FayasNoushad Oh right. Can you update the API link for this, please?

Done 👍

**Review by matheusfelipeog — APPROVED** [review]
Now it's Ok. a big THANKS for the update @FayasNoushad 😄

**Pull request merged**
