### PR TITLE
Add Twilio API

### PR DESCRIPTION
**Pull request by priyanshm07**
- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by priyanshm07** [comment]
Hello, @matheusfelipeog.
I have raised a PR against the label 'hacktoberfest' , waiting for feedback against the PR.

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @priyanshm07, but this API is pay access only:

image

**Comment by priyanshm07** [comment]
@matheusfelipeog Twilio  has a free-tier too

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog Twilio has a free-tier too Under which it provides us free credits when we SignUp. Hope You would consider that

This model is for testing only and when it's over you have to pay.
We don't accept APIs like this, just APIs with some free and renewable tier over a period of time.

**Comment by priyanshm07** [comment]
@matheusfelipeog Ok Got it will try some other APIs.
Well, thanks for the support.

**Pull request closed without merging**
