### PR TITLE
Add Pyschonauts API to Games & Comics

### PR DESCRIPTION
**Pull request by thamudi**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by thamudi** [comment]
For some reason I wasn't able to remove the old commits added by FH089. I ended up scratching the branch and doing it all over. 
My issue was when I was following the squash tutorial I wrote the following git command
```
$ git rebase -i HEAD~4
```
Which caused me to go back 4 commits including FH089.

So, it was my fault for not completely understanding and carefully reading how squashing works.

**Comment by pawelborkar** [comment]
@thamudi 
It's totally fine.
Well I'll suggest using vscode with the gitlens extension as a default code editor for git instead of nano(which comes default). It makes it much easier to squash the commits hence eliminating the errors.

**Review by pawelborkar — APPROVED** [review]
Thanks for the contribution @thamudi

**Comment by thamudi** [comment]
@pawelborkar 
Yeah I agree with you.
And it is my pleasure!

**Pull request merged**
