### PR TITLE
Add RunCodeForMe API

### PR DESCRIPTION
**Pull request by AnnikaV9**
Added RunCodeForMe API to Programming

- [√ ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ √] My addition is ordered alphabetically
- [ √] My submission has a useful description
- [ √] The description does not have more than 100 characters
- [ √] The description does not end with punctuation
- [√ ] Each table column is padded with one space on either side
- [ √] I have searched the repository for any relevant issues or pull requests
- [√ ] Any category I am creating has the minimum requirement of 3 items
- [ √] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by botclimber — APPROVED** [review]
Interesting but the usability is ambiguous, and limited.

**Comment by AnnikaV9** [comment]
> Interesting but the usability is ambiguous, and limited.

I needed a code execution api for one of my projects, and I couldnt find one that was free (Was using Rextester before, but they closed free access to their api). So I decided to make and host one myself.

**Comment by pawelborkar** [comment]
Thanks for opening this PR @AnnikaV9. We appreciate your efforts.

I agree with @botclimber,
The limitation of 1 request/min is huge. Nobody can wait for so long.
I think you should improve the API little bit more and then open a PR. We would happy to review it again and merge it if everything is good.

**Comment by AnnikaV9** [comment]
I don't really have the compute power to process large volumes of requests, hence the high limit. No problem though, I'll make another PR in the future if I ever spend more on a better hosting solution. Thanks for your feedback!

**Comment by pawelborkar** [comment]
>I don't really have the compute power to process large volumes of requests,

Have you considered hosting it on a platform like Heroku or somethings like that? If not then I would suggest you to do so. And a minimum of 25 requests/ min should be good enough for the API of this kind.


>I'll make another PR in the future

Sure. You're absolutely welcome. We would be happy to review and merge your PR 😊

**Comment by AnnikaV9** [comment]
>Have you considered hosting it on a platform like Heroku or somethings like that?

It's not possible to run it on Heroku, as my framework uses cgroups to limit processes. Heroku doesnt give access to cgroups within their dynos. Currently the API is residing in a small single-core Azure VM, but I might try and set up a multi core system locally at my place to host the service.

**Pull request closed without merging**
