### PR TITLE
Updated Smartsheet link to current, old link deprecated

### PR DESCRIPTION
**Pull request by julschong**
- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by pawelborkar — APPROVED** [review]
Thanks for the update @julschong

**Comment by julschong** [comment]
thanks for the awesome repo 👍 @pawelborkar

**Comment by soffieprincess09** [comment]
> * [x]  My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
> * [x]  My addition is ordered alphabetically
> * [x]  My submission has a useful description
> * [x]  The description does not end with punctuation
> * [x]  Each table column is padded with one space on either side
> * [x]  I have searched the repository for any relevant issues or pull requests
> * [x]  Any category I am creating has the minimum requirement of 3 items
> * [x]  All changes have been [squashed](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) into a single commit

**Comment by pawelborkar** [comment]
> thanks for the awesome repo 👍 @pawelborkar

My pleasure 😊

**Comment by cameron187187** [comment]
Hi I’m wondering is this my repo


Sent from Yahoo Mail for iPhone


On Saturday, August 21, 2021, 3:44 AM, Pawel Borkar ***@***.***> wrote:





thanks for the awesome repo 👍 @pawelborkar


My pleasure 😊

**Comment by cameron187187** [comment]
I am xan187 and my Account is stolen. They will use my email and switch back soon


Sent from Yahoo Mail for iPhone


On Saturday, August 21, 2021, 3:44 AM, Pawel Borkar ***@***.***> wrote:





thanks for the awesome repo 👍 @pawelborkar


My pleasure 😊

**Comment by pawelborkar** [comment]
@cameron187187 

Stop spamming the PR section, Otherwise you'll be reported.

**Pull request merged**
