### PR TITLE
Added SurfSpots API

### PR DESCRIPTION
**Pull request by caseydaly**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marekdano** [comment]
Thanks for the contribution @caseydaly!
Can you please update the link? It looks the link of `https://surfspotsapi.com` doesn't work.

**Comment by matheusfelipeog** [comment]
> Can you please update the link? It looks the link of `https://surfspotsapi.com` doesn't work.

@marekdano It looks the API not exists more, I searched and not found

**Comment by caseydaly** [comment]
Hi there,

The API does not exist any more.

**Comment by marekdano** [comment]
> Hi there, The API does not exist any more.

So I'm closing this PR.
Feel free to open a new PR when the API is available again.

**Pull request closed without merging**
