### PR TITLE
Add ScrapingAnt API to the Development category

### PR DESCRIPTION
**Pull request by kami4ka**
I've added the ScrapingAnt API in the README.md file. It's a great API with the availability of free usage.

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marekdano** [comment]
Thanks for the contribution @kami4ka!

Can you please point me to the doc where I can confirm that the API has free usage, please? I cannot find it in the API doc.

**Comment by kami4ka** [comment]
> Thanks for the contribution @kami4ka!
> 
> Can you please point me to the doc where I can confirm that the API has free usage, please? I cannot find it in the API doc.

Sure, it's free for personal use (up to 1000 requests/month): https://scrapingant.com/#pricing

**Comment by marekdano** [comment]
Can you please resolve the conflict?

**Comment by marekdano** [comment]
Can you please solve the failing test? The record has to be in alphabetical order.

Screenshot 2021-04-19 at 08 51 57

**Comment by kami4ka** [comment]
@marekdano sure, done! Thanks!

**Pull request merged**
