### PR TITLE
chore: :wrench: update user-agent

### PR DESCRIPTION
**Pull request by pyaillet**
update httplib2 version in user-agent after dependabot upgrade

### CODE REVIEW

**Comment by yannbertrand** [comment]
Oh yea thanks

**Comment by SitramSoft** [comment]
I tried to use the real user agent from the lib but I still got 404 errors on some websites. From what I could figure out, some websites require a knows user agent, else they return a 404 error. I checked the logs and the 404 errors are back.

Perhaps PR #1428 and#1427 should be reverted.

**Comment by yannbertrand** [comment]
Can you confirm we're talking about https://www.petfinder.com/developers/v2/docs/ and https://www.amiiboapi.com/?

We should not fake our User Agent to validate links. I think we should remove these links if they're not able to answer correctly when given a correct User Agent.

**Comment by SitramSoft** [comment]
https://www.petfinder.com/developers/v2/docs/ and https://www.amiiboapi.com/ are the links I was refering to.

From my tests, I found out that the two websites return a 404 page when accessed with no user agent or a dummy one. When I used Chrome's user agent in the script, a valid page with the description of the API description is returned. 

I chose a user agent from an existing browser in the script since the use case I had in mind was not accessing the API directly but the documentation page. In this use case, the developer which is interested in this API will access the documentation page using a browser first. If the website can be accessed with a browser then from my point of view the link is valid.

It's up to you what you want to do with those two links.

**Comment by yannbertrand** [comment]
I sent an email to Petfinder support and opened [an issue](https://github.com/N3evin/AmiiboAPI/issues/43) on AmiiboAPI. Will wait for them to fix the issue.

**Comment by N3evin** [comment]
Seems to be a host issue. Sorry for the inconvenient. Is it possible to get delisted? I will request again once I decided to change host.

**Comment by yannbertrand** [comment]
Sure thing. Thanks for looking at it. Let us know! 😄

**Pull request merged**
