### PR TITLE
Add Wandbox API to Development

### PR DESCRIPTION
**Pull request by prithvi2k2**
The Wandbox API can compile/interpret code via HTTP POST methods. Visit wandbox.org for info on what languages it supports.
No categories added.

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by prithvi2k2** [comment]
Hi @matheusfelipeog I tested the API in our custom [discord bot](https://github.com/NGIT-Open-Source/Neil.js) and it works flawlessly. Waiting for review. Thank you

**Comment by prithvi2k2** [comment]
Hi @matheusfelipeog , seems like the link has been moved & updated and also it isn't in English anymore, check out https://github.com/melpon/wandbox/blob/master/kennel/API.md

**Comment by matheusfelipeog** [comment]
> Hi @matheusfelipeog , seems like the link has been moved & updated and also it isn't in English anymore, check out https://github.com/melpon/wandbox/blob/master/kennel/API.md

Thanks for letting us know @prithvi2k2, but unfortunately we can't update the link :/

Read more about it at #3104

**Comment by prithvi2k2** [comment]
Seems like @apilayer-admin is commercialising the whole thing, Very sad to see. I understand problems of maintainers like you and am on your side completely.
Thank you for everything ♥️
The Open Source community will never forget your work

**Comment by matheusfelipeog** [comment]
Thank you so much for your support @prithvi2k2, this is very important to us ❤️ 

> And also maybe GitHub should know about this issue, maybe they can help

We've already talked to GitHub reps, and unfortunately, there's not much they can do.

**Pull request merged**
