### PR TITLE
Add NLP Cloud API

### PR DESCRIPTION
**Pull request by juliensalinas**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marekdano** [comment]
Thanks for the contribution @juliensalinas!
Can you please resolve the conflict and [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) all your commits?

**Comment by juliensalinas** [comment]
Thanks @marekdano !
I just resolved the conflict, but I'm unable to squash the commits... I perfectly followed your rebase guide here: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
But for some reason it's not working for me. I have 6 commits to squash but when doing `git rebase -i HEAD~6` I can only see my 3 first commits...
Could you maybe help?
Thanks a lot!

**Comment by marekdano** [comment]
> Thanks @marekdano !
> I just resolved the conflict, but I'm unable to squash the commits... I perfectly followed your rebase guide here: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
> But for some reason it's not working for me. I have 6 commits to squash but when doing `git rebase -i HEAD~6` I can only see my 3 first commits...
> Could you maybe help?
> Thanks a lot!

Please squash the commits that you can see.

**Comment by juliensalinas** [comment]
Done @marekdano !

Thanks!
(and if something is still wrong please don't hesitate to let me know).

**Comment by marekdano** [comment]
@juliensalinas can I ask you to create a new PR for NLP Cloud API? 
I found that this PR has an extra record of 
```
[Sentim-API](https://sentim-api.herokuapp.com) | Text sentiment analysis | No | Yes | Yes |
```
which causes `Validation_link` script to fail because the record is already in README.

**Comment by juliensalinas** [comment]
Sure, no problem.
Here it is: https://github.com/public-apis/public-apis/pull/1663

Thanks @marekdano !

**Pull request merged**
