### PR TITLE
add getfestivo.com

### PR DESCRIPTION
**Pull request by SzymonDukla**
- [X] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [X] My addition is ordered alphabetically
- [X] My submission has a useful description
- [X] The description does not end with punctuation
- [X] Each table column is padded with one space on either side
- [X] I have searched the repository for any relevant issues or pull requests
- [X] Any category I am creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

Adding getfestivo.com in place of holidayapi.pl which was rebranded into back in mid-2018 :)

### CODE REVIEW

**Comment by SzymonDukla** [comment]
hey @marekdano seems all checks passed, would be great if you could merge

**Comment by marekdano** [comment]
Thanks for the contribution @SzymonDukla!

The API doesn't say clearly if it has a free-tier plan and what its conditions are. Can you please point me to a doc to verify that API can be used for free?

**Comment by pawelborkar** [comment]
@SzymonDukla 
> Can you please point me to a doc to verify that API can be used for free?

If you don't have any then also please let us know.

**Comment by CipherGirl** [comment]
@pawelborkar this may be the link https://docs.getfestivo.com/docs/before-you-start. A new PR for this one is created #2091

> @SzymonDukla
> 
> > Can you please point me to a doc to verify that API can be used for free?
> 
> If you don't have any then also please let us know.

**Comment by matheusfelipeog** [comment]
This PR is inactive, so the API was added in another PR/commit.

More information at: #2002

**Pull request closed without merging**
