### PR TITLE
Make CONTRIBUTING.md more precise and clear.

### PR DESCRIPTION
**Pull request by PawelBorkar**
This will make the CONTRIBUTING guide more clear and precise for beginners as well as new contributors.

### CODE REVIEW

**Review by yannbertrand — APPROVED** [review]

**Comment by marekdano** [comment]
@PawelBorkar thanks for putting it down. It's really useful.

**Review by marekdano — APPROVED** [review]

**Comment by PawelBorkar** [comment]
@marekdano 
My pleasure 😊

**Comment by PawelBorkar** [comment]
Just waiting for @matheusfelipeog review 😅

**Review by matheusfelipeog — APPROVED** [review]
Wow, this is very good @PawelBorkar 🎉🎉

**Comment by PawelBorkar** [comment]
Thanks @matheusfelipeog 😊

**Pull request merged**
