### PR TITLE
Add T.LY Link Shortener

### PR DESCRIPTION
**Pull request by timleland**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] Your additions are ordered alphabetically
- [ ] Your submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column should be padded with one space on either side
- [ ] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marekdano** [comment]
@timleland thanks for your contribution!
Can I ask you to add your `T.LY` API in the section alphabetically?

**Comment by timleland** [comment]
@marekdano I updated its placement. Thanks!

**Comment by marekdano** [comment]
> @marekdano I updated its placement. Thanks!

Thanks for the update. I can't see `t.ly` API in README anymore. There is a new API of `rel.ink` instead, but the link doesn't work.

**Comment by timleland** [comment]
Thanks it should be fixed now.

**Comment by PawelBorkar** [comment]
Can you please [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) the commits into a single one?

**Comment by marekdano** [comment]
Closing by duplicate #1605

**Pull request closed without merging**
