### PR TITLE
Add Dev.to API

### PR DESCRIPTION
**Pull request by alestor123**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by alestor123** [comment]
@marekdano its a valid PR you may please merge

**Comment by alestor123** [comment]
@marekdano  Yeah i know it has 2 failed commits but you can just merge the last verfied one

**Comment by PawelBorkar** [comment]
@alestor123 
Sorry we can't do that. Please squash the commits or make a new PR and don't forget to mention this one.

**Comment by pawelborkar** [comment]
@alestor123 Please squash the commits or make a new PR.

**Review by Dawg214 — APPROVED** [review]

**Comment by emeraldivine335** [comment]
https://www.github.com/public-apis/public-apis/tree/a18e1dd19561c2bb72aad5631ea71cae8a672dc2/README.md

**Comment by CipherGirl** [comment]
A new PR #2092 is created for this inactive PR.

**Pull request closed without merging**
