### PR TITLE
Add Singapore Weather Reading API

### PR DESCRIPTION
**Pull request by JWiryo**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by fintzd — APPROVED** [review]
Looks good to me!

**Comment by JWiryo** [comment]
> 
> 
> Looks good to me!

Thank You!

**Review by 0x0is1 — CHANGES_REQUESTED** [review]
Decrease the API description to 100 chars only to pass the build check.
`| [SG Weather Reading](https://data.gov.sg/dataset/realtime-weather-readings) | Realtime weather readings for Singapore area including other weather parameters | No | Yes | Unknown |`

This much description should be enough.

**Comment by JWiryo** [comment]
Updated and Squashed the commit

**Review by 0x0is1 — APPROVED** [review]
LGTM!

**Comment by 0x0is1** [comment]
@matheusfelipeog this is good to go?

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog this is good to go?

Yes 😆

**Comment by matheusfelipeog** [comment]
Thanks for your contribution @JWiryo and thanks for your review @0x0is1 ❤️

**Comment by JWiryo** [comment]
Thank you very much for allowing me to learn on how to contribute to an open-source project

**Pull request merged**
