### PR TITLE
Added bitquery blockchain data APIs to correct order

### PR DESCRIPTION
**Pull request by thefool76**
- | ✔] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- | ✔] My addition is ordered alphabetically
-| ✔] My submission has a useful description
- [ ✔] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by thefool76** [comment]
hey i added the bitquery blockchain data API with correct alphabetical order

**Review by matheusfelipeog — CHANGES_REQUESTED** [review]
Thanks for your contribution @thefool76 😄 

The alphabetical order is still incorrect, this API has to be between Bitmex and Bittrex. Can you fix this, please?

**Comment by matheusfelipeog** [comment]
ref: #1669

**Comment by thefool76** [comment]
@matheusfelipeog sorry for that i fix it .

**Review by matheusfelipeog — APPROVED** [review]
Now it's Ok 😆 

Thanks for the update.

**Comment by thefool76** [comment]
@matheusfelipeog it feels good to contribute :)

**Pull request merged**
