### PR TITLE
Update the link of Launch Library 2 to its homepage for APIs

### PR DESCRIPTION
**Pull request by blokhin**
- [+] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [+] Your additions are ordered alphabetically
- [+] Your submission has a useful description
- [+] The description does not end with punctuation
- [+] Each table column should be padded with one space on either side
- [+] You have searched the repository for any relevant issues or pull requests
- [+] Any category you are creating has the minimum requirement of 3 items
- [+] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by blokhin** [comment]
Your feedback or criticism would be highly appreciated 👋

**Comment by blokhin** [comment]
ping

**Comment by blokhin** [comment]
ping

**Comment by PawelBorkar** [comment]
Hey @blokhin 
Thanks for your contribution.

P.S.:- We don't criticize people over here what we do is appreciate them and give our feedback 😉

**Pull request merged**
