### PR TITLE
Update the link from blockchain.info to blockchain.com

### PR DESCRIPTION
**Pull request by lukas-dallhammer**
I've updated this because the Hyperlink to blockchain doesn't work
(Fixed Link)

### CODE REVIEW

**Comment by PawelBorkar** [comment]
@lukas-dallhammer Thanks for the contribution. Can you please solve the conflict?

**Review by banderalkhaldeyy — APPROVED** [review]

**Review by Marvinrr155q — APPROVED** [review]

**Comment by PawelBorkar** [comment]
Although they have redirected the old link to the present one.
Thanks for updating the link :)

**Comment by PawelBorkar** [comment]
@lukas-dallhammer  Please push to the master branch not to the alpha-site

**Comment by lukas-dallhammer** [comment]
Sorry, it's my first contribution now everything is done, right?

**Comment by PawelBorkar** [comment]
@lukas-dallhammer 
Please make a new PR and set the head to master branch of the public-apis

**Pull request merged**
