### PR TITLE
Remove broken links

### PR DESCRIPTION
**Pull request by iamjoker021**
- [x ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x ] My addition is ordered alphabetically
- [x ] My submission has a useful description
- [x ] The description does not end with punctuation
- [x ] Each table column is padded with one space on either side
- [x ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

| Problem | Broken links in repository (Issue #1590 and #1590)|
|---|---|
| Problem Description | There are about 800 api links among them there are some broken links need to be removed |
| Solution | Instead of manually checking the them I suggest a program(bad_link_filter.py) that would save bad links in separate file so that can be reviewed later |

The program successfully narrowed 800 links to 32 links (Executed on 23-05-2020)

However some of links works return error because of bot security feature in respective webpage

Hence a manual test only on those filtered records in needed

I've done the manual check also and saved them in broken-links.md

### CODE REVIEW

**Comment by pawelbr** [comment]
Hey @iamjoker021 
Thank you so much for making this PR. We appreciate it.

Since its a PR regarding enhancement. All the collaborators need to approve it. So I'll be requesting their reviews as well while giving my own.

**Comment by iamjoker021** [comment]
Sorry I'm new to GitHub could you kindly elaborate what checks failed so that I could correct them. Thanks in advance!

**Review by matheusfelipeog — COMMENTED** [review]
Hi @iamjoker021 😄 

Thanks for your contribution, but I believe that confusion has occurred here.

```
Instead of manually checking the them I suggest a program(bad_link_filter.py) that would save bad links in separate file so that can be reviewed later
```

We, collaborators, do not do manual verification on each of the more than 800 links listed here. We have the [validate_links.py](https://github.com/public-apis/public-apis/blob/master/build/validate_links.py) script that does this job for us, which shows us only the links that may need manual review. This script is executed by [Github Actions](https://docs.github.com/en/actions) and shown the result to us in the [Actions panel](https://github.com/public-apis/public-apis/actions).

An example of this process is here:

image

After manually checking the links returned by the _validate_links.py_ script, we open issues listing the links that need to be deleted or updated so that others can contribute to the project.

Examples of these problems are: #1590 and #1599

The validate_links.py script, in addition to checking for broken links, also checks for links that need to be updated due to redirection (HTTP code> 300 and <399).

Therefore, this pull request is not much different from the _validate_links.py_ script, which, in essence, does the same thing. One of the only differences is to save the broken links in a file, but I don't see any real gain in keeping them since they are broken.

I will wait for the other collaborators to see if there is a different analysis of this Pull Request.

**Review by marekdano — COMMENTED** [review]
@iamjoker021 thanks a mill for your PR and for considering how we can improve the flow of finding the broken links and removing them.

@matheusfelipeog thanks for well explaining the current flow that we have for finding the broken links and how we remove them! 

I think we don't need to have another script for checking the broken links. What if we can improve the [validate_links.py](https://github.com/public-apis/public-apis/blob/master/build/validate_links.py) script? 
I also think that we don't need to have another file for listing all broken links. We can find out the links that return something different than 200 in the [Github Action](https://github.com/public-apis/public-apis/runs/2661825158?check_suite_focus=true) as @matheusfelipeog said above.

What if we add to automatically remove the links which return 404 and we don't want to check them manually before?

**Comment by matheusfelipeog** [comment]
> What if we add to automatically remove the links which return 404 and we don't want to check them manually before?

I particularly prefer to do a manual check in these cases. So I can check if the link is broken due to the discontinuation of the service or change in the address of the page. So in case of discontinuation I can delete it and in case of changing the address of the page I can create a issue informing that the url needs to be updated. 🤔

**Comment by matheusfelipeog** [comment]
The PR author deleted the fork and it looks like we've already made a decision here.

Fechando este PR.

**Pull request closed without merging**
