### PR TITLE
Added developer jobs uk and remoteuk api

### PR DESCRIPTION
**Pull request by russ-stephens**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not have more than 100 characters
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by mouadessalim — APPROVED** [review]
i think it's okay for me.

**Review by mouadessalim — COMMENTED** [review]
I've already reviewed changes. @russ-stephens

**Comment by russ-stephens** [comment]
> 

Sorry must have clicked re-review by accident.

**Comment by Tintwo** [comment]
I would like to be sure if it make sense to add theses 2 feeds to the repo, because it seems to be raw feed and not API (without any doc on website).
Also, according to the [PR Guidelines](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md#pull-request-guidelines) : `Please make sure the API has proper documentation.` (it's a feed, not an API, so you can't query it)

**Comment by mouadessalim** [comment]
> I would like to be sure if it make sense to add theses 2 feeds to the repo, because it seems to be raw feed and not API (without any doc on website). Also, according to the [PR Guidelines](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md#pull-request-guidelines) : `Please make sure the API has proper documentation.` (it's a feed, not an API, so you can't make specific queries on it)

I have a rather mixed opinion on the subject, indeed there is no documentation however the xml can be converted to json and used. There is no need for documentation as websites only have one API output which are: https://developerjobsuk.co.uk/xml and https://remoteuk.co.uk/feed

**Comment by ignacio1995** [comment]
Its okay.

**Comment by matheusfelipeog** [comment]
Hi @russ-stephens 

Thanks for your contribution ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104

**Comment by sheloobsx** [comment]
Why are you guys harassing me what did I do

**Pull request closed without merging**
