### PR TITLE
Removed gofile.io, file download is not working

### PR DESCRIPTION
**Pull request by kamal-hossain**
## Reasons for removing this site
- Download link they are providing is not working.
- They are not providing any direct link to the user who is not a donor.

### CODE REVIEW

**Review by fintzd — APPROVED** [review]
Thanks!

**Comment by marekdano** [comment]
I checked their service and the download works for me.

Can someone else have an issue with the `gofile.io` service too?

**Comment by pawelborkar** [comment]
Yeah, It's working for me as well.

**Comment by matheusfelipeog** [comment]
For me it's also working

**Comment by matheusfelipeog** [comment]
I'm going to close this PR. Looks to me like it was just a temporary problem.

If other people have this kind of problem, please let us know ;)

**Pull request closed without merging**
