### PR TITLE
Add Abstract APIs and new phone category

### PR DESCRIPTION
**Pull request by Emmajperrez**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Comment by Emmajperrez** [comment]
@53jk1 could this be merged in?

**Comment by matheusfelipeog** [comment]
Thanks for contribution @Emmajperrez 😆 

I see that [abstractapi](https://www.abstractapi.com) has many APIs, Isn't it better to add them all separately in this PR?

Example:
https://www.abstractapi.com/user-avatar-api
https://www.abstractapi.com/phone-validation-api
https://www.abstractapi.com/web-scraping-api
and more...

You can add separately or only abstractapi.com in readme. This prevent redundancy.

What do you prefer?

**Comment by Emmajperrez** [comment]
Great idea @matheusfelipeog .
Adding them separately.

**Comment by Emmajperrez** [comment]
@matheusfelipeog @53jk1 just added Abstract APIs and added a new "phone" category 😺

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog @53jk1 just added Abstract APIs and added a new "phone" category 😺

Perfect @Emmajperrez 😆 

Are you going to add the other APIs in this PR?

image

**Comment by Emmajperrez** [comment]
They are in private beta so I guess it's not relevant for now.
I'll make another PR for it later on if it works for you?

**Comment by matheusfelipeog** [comment]
> They are in private beta so I guess it's not relevant for now.
> I'll make another PR for it later on if it works for you?

Oh, right. Ok.

**Review by matheusfelipeog — APPROVED** [review]

**Comment by matheusfelipeog** [comment]
A big THANKS for your contribution @Emmajperrez ❤️ 🎉

**Comment by Emmajperrez** [comment]
A big thank you for jumping in! 🥇 
Excited to see it live!

**Comment by matheusfelipeog** [comment]
Done 🎉

**Pull request merged**
