### PR TITLE
Fix bible

### PR DESCRIPTION
**Pull request by OscarRG**
- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by matheusfelipeog — CHANGES_REQUESTED** [review]
Thanks for your contribution @OscarRG ;)

Looks like you've done other things besides removing the Bible API. Fix this and just remove the Bible API, please.

When finished, you can request my review.

**Comment by matheusfelipeog** [comment]
@OscarRG In case you are having any problems, you can close this PR and open a new one with just the removal of the Bible API.

**Comment by OscarRG** [comment]
@matheusfelipeog that would be great, i have some conflicts

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog that would be great, i have some conflicts

@OscarRG So you can do this ;)

Request my review when opening the new PR

**Comment by OscarRG** [comment]
Hey @matheusfelipeog i think i fixed all the errors that i had. If not, i will just create a new PR :)

**Review by matheusfelipeog — APPROVED** [review]
Now it's Ok ✔🎉

Thanks for the new update @OscarRG <3

**Pull request merged**
