### PR TITLE
Updated authentication for IEX

### PR DESCRIPTION
**Pull request by fabiendv**
The June 15th, [IEX](https://iextrading.com/apps/stocks/) has updated his API by adding authentication to `apiKey`.

### CODE REVIEW

**Comment by yannbertrand** [comment]
Hey Fabien, I can't find that info in the docs. Can you show me where you found it?

**Comment by fabiendv** [comment]
Couldn't find the article. However, the GET (https://api.iextrading.com/1.0/stock/AAPL/quote) is not working any more. You need to register and add the API key (linked to your account) in the request to make it work.

**Comment by yannbertrand** [comment]
Alright I'm merging it then! Thank you for your help

**Comment by fabiendv** [comment]
You're welcome!

**Pull request merged**
