### PR TITLE
Add Httpbin Cloudflare API

### PR DESCRIPTION
**Pull request by fawazahmed0**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by fintzd — APPROVED** [review]
Looks good to me!

**Comment by fintzd** [comment]
By the way, super weird URL, so I checked it out, and weirdly enough it turns out to really be a Cloudflare API. 
CF: this blog post on their official blog: https://blog.cloudflare.com/last-call-for-quic/

**Comment by Tiaogaviao** [comment]
Ganhar dinheiro baixando o Kwai!https://s.kwai.app/s/oenFdtwS

**Review by matheusfelipeog — APPROVED** [review]
Thanks for one more contribution. @fawazahmed0 <3

**Comment by matheusfelipeog** [comment]
> By the way, super weird URL, so I checked it out, and weirdly enough it turns out to really be a Cloudflare API.
> CF: this blog post on their official blog: https://blog.cloudflare.com/last-call-for-quic/

And thanks for letting us know about it @fintzd <3

**Comment by fawazahmed0** [comment]
Thanks @matheusfelipeog

**Pull request merged**
