### PR TITLE
Add Hirak Translation to Text Analysis

### PR DESCRIPTION
**Pull request by FayeNichols**
- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Review by matheusfelipeog — CHANGES_REQUESTED** [review]
Thanks for your contribution @FayeNichols ;)

This API fits better in the [Text Analysis](https://github.com/public-apis/public-apis#text-analysis) category, can you move it there, please?

**Comment by FayeNichols** [comment]
> Thanks for your contribution @FayeNichols ;)
> 
> This API fits better in the [Text Analysis](https://github.com/public-apis/public-apis#text-analysis) category, can you move it there, please?

I don't think so @matheusfelipeog, because it don't analyse the text Text Analysis, i'll add OCR api later to that category! what do you think?

**Comment by matheusfelipeog** [comment]
> I don't think so @matheusfelipeog, because it don't analyse the text Text Analysis, i'll add OCR api later to that category! what do you think?

@FayeNichols But that involves text analysis. Also note that all APIs related to text translations are in the [Text Analysis](https://github.com/public-apis/public-apis#text-analysis) category

**Review by FayeNichols — COMMENTED** [review]
done, thank you :)

**Review by matheusfelipeog — APPROVED** [review]
Now it's ok ✔

Thanks for the update @FayeNichols <3

**Pull request merged**
