### PR TITLE
Add Gazette API 

### PR DESCRIPTION
**Pull request by shailavij**
- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by shailavij** [comment]
Add Gazette API

**Comment by pawelbr** [comment]
Thanks for the contribution @shailavij 

Please point the URL to the API documentation and don't forget to squash all the commits into a single one

**Comment by shailavij** [comment]
Thanks for your comments . I have updated API doc URL in New commit . 

Please let me know how to squash commits in specific branch in fork repository. Kindly share me  any workflow document.

**Comment by pawelbr** [comment]
>Kindly share me any workflow document.

Here you go

https://gitbetter.substack.com/p/how-to-squash-git-commits

**Comment by pawelbr** [comment]
@shailavij 
The API is seem to have OAuth 2.0 authentication.

https://github.com/TheGazette/DevDocs/blob/master/authentication/sign-in.md

**Comment by pawelborkar** [comment]
ref. #2002

**Pull request closed without merging**
