### PR TITLE
Adding Bitquery

### PR DESCRIPTION
**Pull request by buddies2705**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by 61004jack** [comment]
Duplicate of #

**Review by 61004jack — APPROVED** [review]

**Review by matheusfelipeog — CHANGES_REQUESTED** [review]
Thanks for your contribution @buddies2705 ✋ 

Can you fix the alphabetical order, please?

**Review by Javithaboss — APPROVED** [review]

**Comment by thefool76** [comment]
hey @matheusfelipeog can i fix the the alphabetical order ?

**Comment by matheusfelipeog** [comment]
> hey @matheusfelipeog can i fix the the alphabetical order ?

@thefool76 Yes, you can see about inactive PRs here: #2002

**Comment by matheusfelipeog** [comment]
This PR is inactive, so the API was added in another PR/commit.

More information at: #2002

**Pull request closed without merging**
