### PR TITLE
Added ObjectCut as background removal API

### PR DESCRIPTION
**Pull request by AlbertSuarez**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by AlbertSuarez** [comment]
@davemachado Do you have a moment to take a look at this? 😄

**Comment by AlbertSuarez** [comment]
@davemachado Sorry to bother you again, but did you have time to look at this one? Thanks! 😄

**Review by 53jk1 — APPROVED** [review]

**Comment by AlbertSuarez** [comment]
@yannbertrand Do you have a moment to take a look at this? Any modification, feel free to tell me 👍

**Comment by yannbertrand** [comment]
Thanks

**Pull request merged**
